apiVersion: v1
kind: Service
metadata:
  name: {{ include "mycomhelm.fullname" . }}
  labels:
    {{- include "mycomhelm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 5701
      name: hazelcast      
  selector:
    {{- include "mycomhelm.selectorLabels" . | nindent 4 }}
