apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-com-repo-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-com-repo
  template:
    metadata:
      labels:
        app: my-com-repo
    spec:
      containers:
      - name: my-com-repo
        image: shaijuacrrepo1.azurecr.io/shaijutech82/my-com-repo:#{Build.BuildId}#
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: my-com-repo
    k8s-app: my-com-repo
  name: my-com-repo
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  type: LoadBalancer
  selector:
    app: my-com-repo
