apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-com-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-com-app
  template:
    metadata:
      labels:
        app: my-com-app
    spec:
      containers:
      - name: my-com-app
        image: shaijuacrrepo1.azurecr.io/java_spring_shaiju:v4
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        - containerPort: 5701        
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: my-com-app-service
    k8s-app: my-com-app-service
  name: my-com-app-service
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: hazelcast
    port: 5701  
  type: LoadBalancer
  selector:
    app: my-com-app
